apiVersion: v1
kind: Service
metadata:
  name: locust-master
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: locust
    role: master
  ports:
    - name: web-ui
      port: 8089
      targetPort: 8089
    - name: master-p1
      port: 5557
      targetPort: 5557
    - name: master-p2
      port: 5558
      targetPort: 5558

