apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: ordr-order-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class BlazeMeterUser(HttpUser):
        wait_time = between(1, 3)
        host = "https://blazemeter.com"

        @task
        def open_homepage(self):
            # Add a transaction name label
            self.client.get("/", name="Blazemeter Homepage")

        @task
        def open_docs(self):
            # Add a transaction name label
            self.client.get("/docs", name="Blazemeter Docs Page")

        @task
        def open_contact(self):
            # Add one more named transaction
            self.client.get("/contact", name="Blazemeter Contact Page")
