apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: ordr-order-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class BlazeMeterUser(HttpUser):
        wait_time = between(1, 3)
        host = "https://www.blazemeter.com"

        @task
        def open_homepage(self):
            # Don't add "/" â€” this calls the base URL directly
            self.client.get("", name="Blazemeter Homepage")
