apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: ordr-order-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class BlazeMeterUser(HttpUser):
        wait_time = between(1, 3)
        host = "https://blazemeter.com"

        @task
        def open_homepage(self):
            self.client.get("/")

