apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-scripts
  namespace: ordr-order-testing
data:
  locustfile.py: |
    from locust import HttpUser, task, between

    class BlazeMeterUser(HttpUser):
        wait_time = between(1, 3)
        host = "https://www.blazemeter.com"

        @task
        def open_homepage(self):
            # Disable SSL verification
            with self.client.get("", name="Blazemeter Homesam1", verify=False, catch_response=True) as response:
                if response.status_code != 200:
                    response.failure(f"Unexpected status code: {response.status_code}")
